import { $, Glob, write } from "bun"

const appsGlob = new Glob("./apps/**/db/schema.ts")
const appsSchemaFiles = await Array.fromAsync(appsGlob.scan("."))

const pkgGlob = new Glob("./packages/db/schema/*-schema.ts")
const pkgSchemaFiles = await Array.fromAsync(pkgGlob.scan("."))

const imports = [
	...appsSchemaFiles.map((file) => {
		return `export * from "@/${file.replace("./apps/", "").replace(".ts", "")}"`
	}),
	...pkgSchemaFiles.map((file) => {
		return `export * from "./${file.replace("./packages/db/", "").replace(".ts", "")}"`
	}),
]

const content = `// File generated by bun run db:generate:imports\n${imports.join("\n")}\n`

write("./packages/db/schema.ts", content)

await $`biome check --write ./packages/db/schema.ts`

console.log("✅ @/db: Schema imports generated!")
